### PR TITLE
Adding bash script to automate CMake building

### PR DESCRIPTION
**Pull request by vimleshkumarkanaujiya**
Merge the master branch with the forked branch named "bash-script".
The build.sh file makes it easy to build the project

### CODE REVIEW

**Comment by vishal-ahirwar** [comment]
Thank you for your Contribution but
This isn't cross-platform thing this would work only on unix based system check the header file newton.h  setup() method need implementation 
setup(){
1. it should add itself to system path
2. it should check if cmake and g++ compiler installed or not if not it should download and setup everything for user.
};

for this we can use boost or poco c++ API

**Comment by vimleshkumarkanaujiya** [comment]
Thanks for your knowledge!

**Comment by vishal-ahirwar** [comment]
Sorry I forgot to mention build.sh has no use as of now why someone clone a repo again if they have already cloned it 
please  update the build file

**Comment by vishal-ahirwar** [comment]
you can add other command like downloading cmake or g++ compiler if it's already not present in user system

**Pull request merged**
